HUGGING_FACE_USER_ACCESS_TOKEN: ""
LOG_LEVEL: 10
HUGGING_FACE_REPO_ID: "the-ride-never-ends/american_law"
OPENAI_MODEL: "gpt-4o" # Options: gpt-4o, gpt-4-turbo, gpt-4, gpt-3.5-turbo
OPENAI_EMBEDDING_MODEL: "text-embedding-3-small"
OPENAI_API_KEY: ""