# docker/docker-compose.yml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - LOG_LEVEL=20
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGING_FACE_USER_ACCESS_TOKEN=${HUGGING_FACE_USER_ACCESS_TOKEN}
    volumes:
      - ./data:/data
      - ./app/configs.yaml:/app/configs.yaml
      - ./frontend:/frontend
    restart: unless-stopped
