# Production Docker Compose with Nginx Reverse Proxy and SSL
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - LOG_LEVEL=20
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGING_FACE_USER_ACCESS_TOKEN=${HUGGING_FACE_USER_ACCESS_TOKEN}
    volumes:
      - ./data:/data
      - ./frontend:/frontend
    restart: unless-stopped
    networks:
      - app-network
    # Remove port exposure since nginx will handle it
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    command: certbot renew --quiet
    restart: "no"

networks:
  app-network:
    driver: bridge

volumes:
  letsencrypt:
  certbot-www: