# docker/docker-compose.dev.yml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - LOG_LEVEL=10
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGING_FACE_USER_ACCESS_TOKEN=${HUGGING_FACE_USER_ACCESS_TOKEN}
    volumes:
      - ../app:/app
      - ../data:/app/data
      - ../app/configs.yaml:/app/configs.yaml
