# docker/docker-compose.dev.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - LOG_LEVEL=10
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ../app:/app
      - ../data:/app/data
      - ../app/config.yaml:/app/config.yaml
