name: Law Search CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f lawdb/requirements.txt ]; then
          pip install -r lawdb/requirements.txt
        fi
        pip install -e lawdb
        
    - name: Run tests
      run: |
        cd lawdb
        python -m pytest
        
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f lawdb/requirements.txt ]; then
          pip install -r lawdb/requirements.txt
        fi
        pip install -e lawdb
        
    - name: Build package
      run: |
        cd lawdb
        python setup.py sdist bdist_wheel
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: lawdb/dist/ 